---
title: "MiniProject2"
author: "Sumeet Mishra"
date: "3/9/2019"
output: pdf_document
---

```{r}
library(ggplot2)
library(dplyr)
library(ggpubr)
DFP=read.csv('DFP_WTHH_release.csv', header = TRUE)
#View(DFP)
myvars<-c("presvote16post","house3","weight_DFP","M4A","GREENJOB","WEALTH","MARLEG","ICE","GUNS","POP_1","POP_2","POP_3")
dfp1<-DFP[myvars]
issue_variables=c("M4A","GREENJOB","WEALTH","MARLEG","ICE","GUNS")
#View(dfp1)
```



```{r}
dfp1$vote_status <- ifelse(dfp1$presvote16post != 1 & dfp1$house3==1, 1, ifelse(dfp1$presvote16post != 2 & dfp1$house3==2, 2,3))
#dfp1=dfp1%>%filter(dfp1$M4A<6)
#dfp1=subset(dfp1,dfp1$M4A!=6|dfp1$GREENJOB!=6|dfp1$WEALTH!=6|dfp1$MARLEG!=6|dfp1$ICE!=6|dfp1$GUNS!=6)
#View(dfp1)
dfp10=subset(dfp1,vote_status==c(1,2))
df_m4a=subset(dfp10,M4A==c(1,2,3,4,5))
df_greenjob=subset(dfp10,GREENJOB==c(1,2,3,4,5))
df_wealth=subset(dfp10,WEALTH==c(1,2,3,4,5))
df_marleg=subset(dfp10,MARLEG==c(1,2,3,4,5))
df_ice=subset(dfp10,ICE==c(1,2,3,4,5))
df_guns=subset(dfp10,GUNS==c(1,2,3,4,5))
#View(df_m4a)




#View(dfp10)

```


```{r}
m4a=ggplot(df_m4a,aes(x=M4A,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 5)) + scale_fill_manual(values=c( "#56B4E9","#999999"), 
                       name="Swing Voter's Status",
                       breaks=c("1", "2"),
                       labels=c("Switch to Democrat", "Switch to Republican"))
greenjob=ggplot(df_greenjob,aes(x=GREENJOB,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 5))+ scale_fill_manual(values=c( "#56B4E9","#999999"), 
                       name="Swing Voter's Status",
                       breaks=c("1", "2"),
                       labels=c("Switch to Democrat", "Switch to Republican"))

wealth=ggplot(df_wealth,aes(x=WEALTH,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 5))+ scale_fill_manual(values=c( "#56B4E9","#999999"), 
                       name="Swing Voter's Status",
                       breaks=c("1", "2"),
                       labels=c("Switch to Democrat", "Switch to Republican"))
 
marleg=ggplot(df_marleg,aes(x=MARLEG,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 5))+ scale_fill_manual(values=c( "#56B4E9","#999999"), 
                       name="Swing Voter's Status",
                       breaks=c("1", "2"),
                       labels=c("Switch to Democrat", "Switch to Republican"))

ice=ggplot(df_ice,aes(x=ICE,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 5))+ scale_fill_manual(values=c( "#56B4E9","#999999"), 
                       name="Swing Voter's Status",
                       breaks=c("1", "2"),
                       labels=c("Switch to Democrat", "Switch to Republican"))

guns=ggplot(df_guns,aes(x=GUNS,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 5))+ scale_fill_manual(values=c( "#56B4E9","#999999"), 
                       name="Swing Voter's Status",
                       breaks=c("1", "2"),
                       labels=c("Switch to Democrat", "Switch to Republican"))
 
ggarrange(m4a, greenjob, wealth,marleg,ice,guns, ncol = 2, nrow = 3,common.legend = TRUE)

```

```{r}
dfp1$vote_status <- ifelse(dfp1$presvote16post == dfp1$house3, dfp1$house3, 10)
dfp3=subset(dfp1,vote_status==c(1,2,10))
df_m4a2=subset(dfp3,M4A==c(1,2,3,4,5))
df_greenjob2=subset(dfp3,GREENJOB==c(1,2,3,4,5))
df_wealth2=subset(dfp3,WEALTH==c(1,2,3,4,5))
df_marleg2=subset(dfp3,MARLEG==c(1,2,3,4,5))
df_ice2=subset(dfp3,ICE==c(1,2,3,4,5))
df_guns2=subset(dfp3,GUNS==c(1,2,3,4,5))

#View(dfp3)
```

```{r}
m4a2=ggplot(df_m4a2,aes(x=M4A,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 6)) + scale_fill_manual(values=c( "#E69F00","#009E73","#999999"), 
                       name="Voter's Status",
                       breaks=c("1", "2","10"),
                       labels=c("Loyal Democrats", "Loyal Republicans","Swing Voters"))
greenjob2=ggplot(df_greenjob2,aes(x=GREENJOB,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 6)) + scale_fill_manual(values=c( "#E69F00","#009E73","#999999"), 
                       name="Voter's Status",
                       breaks=c("1", "2","10"),
                       labels=c("Loyal Democrats", "Loyal Republicans","Swing Voters"))
wealth2=ggplot(df_wealth2,aes(x=WEALTH,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 6)) + scale_fill_manual(values=c( "#E69F00","#009E73","#999999"), 
                       name="Voter's Status",
                       breaks=c("1", "2","10"),
                       labels=c("Loyal Democrats", "Loyal Republicans","Swing Voters"))
marleg2=ggplot(df_marleg2,aes(x=MARLEG,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 6)) + scale_fill_manual(values=c( "#E69F00","#009E73","#999999"), 
                       name="Voter's Status",
                       breaks=c("1", "2","10"),
                       labels=c("Loyal Democrats", "Loyal Republicans","Swing Voters"))
ice2=ggplot(df_ice2,aes(x=ICE,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 6)) + scale_fill_manual(values=c( "#E69F00","#009E73","#999999"), 
                       name="Voter's Status",
                       breaks=c("1", "2","10"),
                       labels=c("Loyal Democrats", "Loyal Republicans","Swing Voters"))
guns2=ggplot(df_guns2,aes(x=GUNS,weight=weight_DFP,fill=factor(vote_status)))+geom_histogram(position="dodge",binwidth=0.5)+theme_bw()+scale_x_continuous(breaks = seq(1, 6)) + scale_fill_manual(values=c( "#E69F00","#009E73","#999999"), 
                       name="Voter's Status",
                       breaks=c("1", "2","10"),
                       labels=c("Loyal Democrats", "Loyal Republicans","Swing Voters"))
ggarrange(m4a2, greenjob2, wealth2,marleg2,ice2,guns2, ncol = 2, nrow = 3,common.legend = TRUE)
```

```{r}
#dfp.lo = loess( vote_status~M4A*ICE , data =dfp1, span = 0.25, family="symmetric", normalize=FALSE)
library(GGally)
myvars1<-c("M4A","GREENJOB","WEALTH","MARLEG","ICE","GUNS","vote_status")
dfp5=dfp1[myvars1]
ggpairs(dfp5)
```

```{r}
our.logit=function(x){
coe = coef(swing.weighted.logit)
y = coe[1]+coe[2]*x 
return (exp(y)/(1 + exp(y)))
}


#dfp1$vote_status <- ifelse(dfp1$presvote16post == dfp1$house3, dfp1$house3, 10)
dfp4=subset(dfp1)
dfp4$swing_voter_status <- ifelse(dfp4$vote_status!=10,0,1)
#View(dfp4)
dfp_p.lo = loess( swing_voter_status~POP_1*POP_2*POP_3 , data =dfp4, span = 1, family="symmetric", normalize=FALSE)
newdata1 = expand.grid(POP_1 = seq(1, 5, 1), POP_2 = seq(1, 5, 1),POP_3 = seq(1, 5, 1))
dfp_p.pred1 = predict(dfp_p.lo, newdata = newdata1)
dfp_p.pred1 = data.frame(newdata1, predicted_swing_voter_status = as.vector(dfp_p.pred1)) 
#ggplot(dfp_p.pred1, aes( x = predicted_swing_voter_status, y=..density..,fill =(predicted_swing_voter_status))) + geom_histogram(abcd) 
ggplot(dfp_p.pred1, aes( y = predicted_swing_voter_status,x=POP_1,group=POP_2,color =POP_2)) + geom_point()+ stat_function(fun = our.logit, color = "orange")

```


```{r}
weight.prop = summarise(group_by(dfp4,'M4A','GREENJOB','WEALTH','MARLEG','ICE','GUNS'), weighted.mean(vote_status, w = weight_DFP, na.rm = TRUE))
names(weight.prop) = c('M4A','GREENJOB','WEALTH','MARLEG','ICE','GUNS','prop.swing_voter_status')
t(weight.prop)
ggplot(t(weight.prop), aes(x=c(M4A,GREENJOB,WEALTH,MARLRG,ICE,GUNS),y = prop.swing_voter_status)) + geom_point() 

```

```{r}
 swing.weighted.logit = glm(swing_voter_status ~ POP_1+POP_2+POP_3, family = quasibinomial, weights =weight_DFP , data = dfp4)

our.logit=function(x){
coe = coef(swing.weighted.logit)
y = coe[1]+coe[2]*x 
return (exp(y)/(1 + exp(y)))
}

 ggplot(dfp4, aes(x = POP_1, y = swing_voter_status)) + geom_jitter(height = 0.1,
width = 0.25) + geom_smooth(method = "glm", method.args = list(family = "binomial"), se = FALSE, color = "blue") + stat_function(fun = our.logit, color = "orange")

```

```{r}
swing.weighted.logit = glm(swing_voter_status ~ POP_1+POP_2, family = quasibinomial, weights =weight_DFP , data = dfp4)
pop.df = expand.grid(POP_1=seq(1,5,1),POP_2=seq(1,5,1),POP_3=seq(1,5,1))
pop.pred = predict( swing.weighted.logit, type = "response", newdata = pop.df)
pop.pred.df = data.frame(pop.df, swing.prob = as.vector(pop.pred)) 
ggplot(pop.pred.df, aes(x = POP_1, y = swing.prob,group=POP_2,color=POP_2)) +geom_line()+scale_x_continuous(breaks = seq(1, 5))+theme_bw() 
ggplot(pop.pred.df, aes(x = POP_2, y = swing.prob,group=POP_3,color=POP_3)) +geom_line()+scale_x_continuous(breaks = seq(1, 5))+theme_bw()  
ggplot(pop.pred.df, aes(x = POP_1, y = swing.prob,group=POP_3,color=POP_3)) +geom_line()+scale_x_continuous(breaks = seq(1, 5))+theme_bw() 
#+ xlab("Distance from nearest safe well") + ylab("Probability of switching labs(color = "Arsenic concentration")
#summary( swing.weighted.logit )

```
